### ISSUE TITLE
Update node support

### ISSUE THREAD

**Issue by m1ga** [tidev/node-ios-device#81]
See https://github.com/tidev/node-ios-device/pull/74 for details (its to support node 17)

node 19 tries to download  `https://github.com/tidev/node-ios-device/releases/download/v1.9.4/node_ios_device-v1.9.4-node-v111-darwin-arm64.tar.gz`
node 18 `https://github.com/tidev/node-ios-device/releases/download/v1.9.4/node_ios_device-v1.9.4-node-v108-darwin-x64.tar.gz`

**Comment by cb1kenobi** [comment]
Sigh... I'll have to commandeer the wife's MacBook Pro this weekend :)

**Comment by ewanharris** [comment]
I made #82 that achieves this, it's not perfect for sure but it's probably the quickest/path of least resistance to supporting newer versions of node without any changes in ioslib/the SDK itself

**Comment by cb1kenobi** [comment]
Awesome, I'll give it a look hopefully tonight!
