### ISSUE TITLE
Node 22 support

### ISSUE THREAD

**Issue by m1ga** [tidev/node-ios-device#87]
would it be possible to update https://github.com/tidev/node-ios-device/pull/84 for Node 22?

**Comment by cb1kenobi** [comment]
node-ios-device 3 should already support Node 22. We should update ioslib to use it.

**Comment by m1ga** [comment]
there is no `node_ios_device-v1.11.0-node-v127-darwin-arm64.tar.gz`. There was one slack report where it tried to download the v127 with node 22.3.0 and that file is not in the https://github.com/tidev/node-ios-device/releases/tag/v1.11.0 assets list

**Comment by cb1kenobi** [comment]
Right. We could see about adding support for Node 22, or we could update ioslib to node-ios-device@3. I don't know the level of effort, but it's probably not bad.

FYI, I plan to migrate node-ios-device@3 to ESM and release it as v4, so we should clean up v3, then use that. Besides, v3 has some nice features aside from being futureproofed.

**Comment by m1ga** [comment]
ah, now I get it :smile: I forgot that there is a v1 / v3 here. The PR above looked like a quick way to add support in a short term but since we are going to update ioslib for the new Xcode version we could go to v3/v4 too :+1:

**Comment by cb1kenobi** [comment]
Bingo. So I can clean up v3 (deps, verify Node 22, etc), but no ESM. Then we can update ioslib to use v3. After all that, then I'll move node-ios-device to ESM and call it v4.

**Comment by ewanharris** [comment]
Adding Node 22 support to the existing 1.X version was simple enough to fit into my lunch break so made #88 🙂

**Comment by cb1kenobi** [comment]
node-ios-device@1.12.0 published
